### ISSUE TITLE
How I use?!?

### ISSUE THREAD

**Issue by GavBurke** [ipedrazas/kubernetes-snippets#13]
So i've installed the extension now, no auto-complete comes up for deployments, services etc. when I start typing.  I've ensured the extension is installed and enabled (it restarted VS Code for me) but still nothing ...

**Comment by GavBurke** [comment]
Installed a YAML plugin also, which then reloaded again and now works ... :man_shrugging:

**Comment by Tokenyet** [comment]
Although this is closed thread, It need to be noticed that YAML plugin that supported by Red Hat have **Kubernetes** built-in also.
