### ISSUE TITLE
Addon not updated in marketplace?

### ISSUE THREAD

**Issue by DonMartin76** [ipedrazas/kubernetes-snippets#5]
Hi!

Thanks for a great addon for VSCode!

I stumbled over the `Cluster` vs. `ClusterIP` service type, and wanted to fix that, but I see it has already been fixed in code. But apparently the fixes have not been pushed to the marketplace? I still sit on version 0.1.3 from looong ago (Nov 2016), and there doesn't seem to be any updates.

Am I doing something wrong, or haven't you pushed since 0.1.3? It would be awesome to get an update, and I would also be willing to add some more snippets if welcome.

Best regards, Martin

**Comment by ipedrazas** [comment]
Just published `0.1.8`  🙌

**Comment by DonMartin76** [comment]
Thanks!
